name: On Tag

run-name: Tagged ${{ github.ref }} by @${{ github.actor }}

on:
  push:
    # branches: [main]
    tags:
      # aaa/v0.0.0, aaa/v0.0.0-rc1, bbb/v0.0.0-next.0
      # - '[-_.a-zA-Z]+\/v[0-9]+\.[0-9]+\.[0-9]+-*[-_.a-zA-Z]*'
      - 'release/dev/aaa'
      # - 'deploy/**'
      # - 'release/[-_.a-zA-Z]/*'

env:
  REGISTRY: 'ghcr.io'
  GHCR_PACKAGE_BASE_URL: 'https://github.com/rhiokim/seed-monorepo/pkgs/container/seed-monorepo%2F'

jobs:
  push-create-tag:
    if: startsWith(github.ref, 'refs/tags')
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]

    steps:
      - uses: rhiokim/split-by@master
        id: get-ref
        with:
          string: ${{ github.ref }}
          split-by: '/'

      - name: Print Inputs
        run: |
          echo "environment: ${{ steps.get-ref.outputs._3 }}"
          echo "package: ${{ steps.get-ref.outputs._4 }}"
          echo "action: ${{ steps.get-ref.outputs._2 }}"

      - name: Set env `dotenv=development`
        if: inputs.environment == 'dev'
        run: |
          echo "dotenv=development" >> $GITHUB_ENV

      - name: Set env `dotenv=staging`
        if: inputs.environment == 'staging'
        run: |
          echo "dotenv=staging" >> $GITHUB_ENV

      - name: Set env `dotenv=production`
        if: inputs.environment == 'prod'
        run: |
          echo "dotenv=production" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1
